// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.23.4
// source: grpc/tradeapi/v1/assets/assets_service.proto

package assets

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	date "google.golang.org/genproto/googleapis/type/date"
	decimal "google.golang.org/genproto/googleapis/type/decimal"
	interval "google.golang.org/genproto/googleapis/type/interval"
	money "google.golang.org/genproto/googleapis/type/money"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Тип опциона
type Option_Type int32

const (
	// Неопределенное значение
	Option_TYPE_UNSPECIFIED Option_Type = 0
	// Колл
	Option_TYPE_CALL Option_Type = 1
	// Пут
	Option_TYPE_PUT Option_Type = 2
)

// Enum value maps for Option_Type.
var (
	Option_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_CALL",
		2: "TYPE_PUT",
	}
	Option_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_CALL":        1,
		"TYPE_PUT":         2,
	}
)

func (x Option_Type) Enum() *Option_Type {
	p := new(Option_Type)
	*p = x
	return p
}

func (x Option_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Option_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_enumTypes[0].Descriptor()
}

func (Option_Type) Type() protoreflect.EnumType {
	return &file_grpc_tradeapi_v1_assets_assets_service_proto_enumTypes[0]
}

func (x Option_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Option_Type.Descriptor instead.
func (Option_Type) EnumDescriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{16, 0}
}

// Статус
type Longable_Status int32

const (
	// Не доступен
	Longable_NOT_AVAILABLE Longable_Status = 0
	// Доступен
	Longable_AVAILABLE Longable_Status = 1
	// Запрещено на уровне счета
	Longable_ACCOUNT_NOT_APPROVED Longable_Status = 2
)

// Enum value maps for Longable_Status.
var (
	Longable_Status_name = map[int32]string{
		0: "NOT_AVAILABLE",
		1: "AVAILABLE",
		2: "ACCOUNT_NOT_APPROVED",
	}
	Longable_Status_value = map[string]int32{
		"NOT_AVAILABLE":        0,
		"AVAILABLE":            1,
		"ACCOUNT_NOT_APPROVED": 2,
	}
)

func (x Longable_Status) Enum() *Longable_Status {
	p := new(Longable_Status)
	*p = x
	return p
}

func (x Longable_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Longable_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_enumTypes[1].Descriptor()
}

func (Longable_Status) Type() protoreflect.EnumType {
	return &file_grpc_tradeapi_v1_assets_assets_service_proto_enumTypes[1]
}

func (x Longable_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Longable_Status.Descriptor instead.
func (Longable_Status) EnumDescriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{17, 0}
}

// Статус
type Shortable_Status int32

const (
	// Не доступен
	Shortable_NOT_AVAILABLE Shortable_Status = 0
	// Доступен
	Shortable_AVAILABLE Shortable_Status = 1
	// Признак того, что бумага Hard To Borrow (если есть)
	Shortable_HTB Shortable_Status = 2
	// Запрещено на уровне счета
	Shortable_ACCOUNT_NOT_APPROVED Shortable_Status = 3
	// Разрешено в составе стратегии
	Shortable_AVAILABLE_STRATEGY Shortable_Status = 4
)

// Enum value maps for Shortable_Status.
var (
	Shortable_Status_name = map[int32]string{
		0: "NOT_AVAILABLE",
		1: "AVAILABLE",
		2: "HTB",
		3: "ACCOUNT_NOT_APPROVED",
		4: "AVAILABLE_STRATEGY",
	}
	Shortable_Status_value = map[string]int32{
		"NOT_AVAILABLE":        0,
		"AVAILABLE":            1,
		"HTB":                  2,
		"ACCOUNT_NOT_APPROVED": 3,
		"AVAILABLE_STRATEGY":   4,
	}
)

func (x Shortable_Status) Enum() *Shortable_Status {
	p := new(Shortable_Status)
	*p = x
	return p
}

func (x Shortable_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Shortable_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_enumTypes[2].Descriptor()
}

func (Shortable_Status) Type() protoreflect.EnumType {
	return &file_grpc_tradeapi_v1_assets_assets_service_proto_enumTypes[2]
}

func (x Shortable_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Shortable_Status.Descriptor instead.
func (Shortable_Status) EnumDescriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{18, 0}
}

// Запрос получения списка доступных бирж
type ExchangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangesRequest) Reset() {
	*x = ExchangesRequest{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangesRequest) ProtoMessage() {}

func (x *ExchangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangesRequest.ProtoReflect.Descriptor instead.
func (*ExchangesRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{0}
}

// Список доступных бирж
type ExchangesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Информация о бирже
	Exchanges     []*Exchange `protobuf:"bytes,1,rep,name=exchanges,proto3" json:"exchanges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangesResponse) Reset() {
	*x = ExchangesResponse{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangesResponse) ProtoMessage() {}

func (x *ExchangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangesResponse.ProtoReflect.Descriptor instead.
func (*ExchangesResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{1}
}

func (x *ExchangesResponse) GetExchanges() []*Exchange {
	if x != nil {
		return x.Exchanges
	}
	return nil
}

// Запрос получения списка доступных инструментов
type AssetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetsRequest) Reset() {
	*x = AssetsRequest{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetsRequest) ProtoMessage() {}

func (x *AssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetsRequest.ProtoReflect.Descriptor instead.
func (*AssetsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{2}
}

// Список доступных инструментов
type AssetsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Информация об инструменте
	Assets        []*Asset `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetsResponse) Reset() {
	*x = AssetsResponse{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetsResponse) ProtoMessage() {}

func (x *AssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetsResponse.ProtoReflect.Descriptor instead.
func (*AssetsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{3}
}

func (x *AssetsResponse) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

// Запрос получения информации по конкретному инструменту
type GetAssetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Символ инструмента
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// ID аккаунта для которого будет подбираться информация по инструменту
	AccountId     string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetRequest) Reset() {
	*x = GetAssetRequest{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetRequest) ProtoMessage() {}

func (x *GetAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetRequest.ProtoReflect.Descriptor instead.
func (*GetAssetRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetAssetRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetAssetRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

// Список информации по конкретному инструменту
type GetAssetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Код режима торгов
	Board string `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	// Идентификатор инструмента
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Тикер инструмента
	Ticker string `protobuf:"bytes,3,opt,name=ticker,proto3" json:"ticker,omitempty"`
	// mic идентификатор биржи
	Mic string `protobuf:"bytes,4,opt,name=mic,proto3" json:"mic,omitempty"`
	// Isin идентификатор инструмента
	Isin string `protobuf:"bytes,5,opt,name=isin,proto3" json:"isin,omitempty"`
	// Тип инструмента
	Type string `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	// Наименование инструмента
	Name string `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	// Кол-во десятичных знаков в цене
	Decimals int32 `protobuf:"varint,10,opt,name=decimals,proto3" json:"decimals,omitempty"`
	// Минимальный шаг цены. Для расчета финального ценового шага: min_step/(10ˆdecimals)
	MinStep int64 `protobuf:"varint,11,opt,name=min_step,json=minStep,proto3" json:"min_step,omitempty"`
	// Кол-во штук в лоте
	LotSize *decimal.Decimal `protobuf:"bytes,9,opt,name=lot_size,json=lotSize,proto3" json:"lot_size,omitempty"`
	// Дата экспирации фьючерса
	ExpirationDate *date.Date `protobuf:"bytes,12,opt,name=expiration_date,json=expirationDate,proto3" json:"expiration_date,omitempty"`
	// Валюта котировки, может не совпадать с валютой режима торгов инструмента
	QuoteCurrency string `protobuf:"bytes,13,opt,name=quote_currency,json=quoteCurrency,proto3" json:"quote_currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetResponse) Reset() {
	*x = GetAssetResponse{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetResponse) ProtoMessage() {}

func (x *GetAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetResponse.ProtoReflect.Descriptor instead.
func (*GetAssetResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetAssetResponse) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

func (x *GetAssetResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetAssetResponse) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *GetAssetResponse) GetMic() string {
	if x != nil {
		return x.Mic
	}
	return ""
}

func (x *GetAssetResponse) GetIsin() string {
	if x != nil {
		return x.Isin
	}
	return ""
}

func (x *GetAssetResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetAssetResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetAssetResponse) GetDecimals() int32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *GetAssetResponse) GetMinStep() int64 {
	if x != nil {
		return x.MinStep
	}
	return 0
}

func (x *GetAssetResponse) GetLotSize() *decimal.Decimal {
	if x != nil {
		return x.LotSize
	}
	return nil
}

func (x *GetAssetResponse) GetExpirationDate() *date.Date {
	if x != nil {
		return x.ExpirationDate
	}
	return nil
}

func (x *GetAssetResponse) GetQuoteCurrency() string {
	if x != nil {
		return x.QuoteCurrency
	}
	return ""
}

// Запрос торговых параметров инструмента
type GetAssetParamsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Символ инструмента
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// ID аккаунта для которого будут подбираться торговые параметры
	AccountId     string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetParamsRequest) Reset() {
	*x = GetAssetParamsRequest{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetParamsRequest) ProtoMessage() {}

func (x *GetAssetParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetParamsRequest.ProtoReflect.Descriptor instead.
func (*GetAssetParamsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetAssetParamsRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetAssetParamsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

// Торговые параметры инструмента
type GetAssetParamsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Символ инструмента
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// ID аккаунта для которого подбираются торговые параметры
	AccountId string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Доступны ли торговые операции
	// Старое поле, помечено как устаревшее.
	// Клиентам следует перейти на is_tradeable.
	//
	// Deprecated: Marked as deprecated in grpc/tradeapi/v1/assets/assets_service.proto.
	Tradeable bool `protobuf:"varint,3,opt,name=tradeable,proto3" json:"tradeable,omitempty"`
	// Доступны ли операции в Лонг
	Longable *Longable `protobuf:"bytes,4,opt,name=longable,proto3" json:"longable,omitempty"`
	// Доступны ли операции в Шорт
	Shortable *Shortable `protobuf:"bytes,5,opt,name=shortable,proto3" json:"shortable,omitempty"`
	// Ставка риска для операции в Лонг
	LongRiskRate *decimal.Decimal `protobuf:"bytes,6,opt,name=long_risk_rate,json=longRiskRate,proto3" json:"long_risk_rate,omitempty"`
	// Сумма обеспечения для поддержания позиции Лонг
	//
	// Deprecated: Marked as deprecated in grpc/tradeapi/v1/assets/assets_service.proto.
	LongCollateral *money.Money `protobuf:"bytes,7,opt,name=long_collateral,json=longCollateral,proto3" json:"long_collateral,omitempty"`
	// Ставка риска для операции в Шорт
	ShortRiskRate *decimal.Decimal `protobuf:"bytes,8,opt,name=short_risk_rate,json=shortRiskRate,proto3" json:"short_risk_rate,omitempty"`
	// Сумма обеспечения для поддержания позиции Шорт
	//
	// Deprecated: Marked as deprecated in grpc/tradeapi/v1/assets/assets_service.proto.
	ShortCollateral *money.Money `protobuf:"bytes,9,opt,name=short_collateral,json=shortCollateral,proto3" json:"short_collateral,omitempty"`
	// Начальные требования, сколько на счету должно быть свободных денежных средств, чтобы открыть лонг позицию, для FORTS счетов равен биржевому ГО
	LongInitialMargin *money.Money `protobuf:"bytes,10,opt,name=long_initial_margin,json=longInitialMargin,proto3" json:"long_initial_margin,omitempty"`
	// Начальные требования, сколько на счету должно быть свободных денежных средств, чтобы открыть шорт позицию, для FORTS счетов равен биржевому ГО
	ShortInitialMargin *money.Money `protobuf:"bytes,11,opt,name=short_initial_margin,json=shortInitialMargin,proto3" json:"short_initial_margin,omitempty"`
	// Доступны ли торговые операции
	// Новое поле. Позволяет различать false и "не установлено".
	IsTradable    *wrapperspb.BoolValue `protobuf:"bytes,12,opt,name=is_tradable,json=isTradable,proto3" json:"is_tradable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetParamsResponse) Reset() {
	*x = GetAssetParamsResponse{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetParamsResponse) ProtoMessage() {}

func (x *GetAssetParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetParamsResponse.ProtoReflect.Descriptor instead.
func (*GetAssetParamsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetAssetParamsResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetAssetParamsResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

// Deprecated: Marked as deprecated in grpc/tradeapi/v1/assets/assets_service.proto.
func (x *GetAssetParamsResponse) GetTradeable() bool {
	if x != nil {
		return x.Tradeable
	}
	return false
}

func (x *GetAssetParamsResponse) GetLongable() *Longable {
	if x != nil {
		return x.Longable
	}
	return nil
}

func (x *GetAssetParamsResponse) GetShortable() *Shortable {
	if x != nil {
		return x.Shortable
	}
	return nil
}

func (x *GetAssetParamsResponse) GetLongRiskRate() *decimal.Decimal {
	if x != nil {
		return x.LongRiskRate
	}
	return nil
}

// Deprecated: Marked as deprecated in grpc/tradeapi/v1/assets/assets_service.proto.
func (x *GetAssetParamsResponse) GetLongCollateral() *money.Money {
	if x != nil {
		return x.LongCollateral
	}
	return nil
}

func (x *GetAssetParamsResponse) GetShortRiskRate() *decimal.Decimal {
	if x != nil {
		return x.ShortRiskRate
	}
	return nil
}

// Deprecated: Marked as deprecated in grpc/tradeapi/v1/assets/assets_service.proto.
func (x *GetAssetParamsResponse) GetShortCollateral() *money.Money {
	if x != nil {
		return x.ShortCollateral
	}
	return nil
}

func (x *GetAssetParamsResponse) GetLongInitialMargin() *money.Money {
	if x != nil {
		return x.LongInitialMargin
	}
	return nil
}

func (x *GetAssetParamsResponse) GetShortInitialMargin() *money.Money {
	if x != nil {
		return x.ShortInitialMargin
	}
	return nil
}

func (x *GetAssetParamsResponse) GetIsTradable() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsTradable
	}
	return nil
}

// Запрос получения цепочки опционов
type OptionsChainRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Символ базового актива опциона
	UnderlyingSymbol string `protobuf:"bytes,1,opt,name=underlying_symbol,json=underlyingSymbol,proto3" json:"underlying_symbol,omitempty"`
	// Опциональный параметр. Актуален для опционов на фьючерсы, по типу (недельные, месячные).
	// Если параметр не указан, будут возвращены опционы с ближайшей датой экспирации.
	Root string `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	// Опциональный фильтр по дате экспирации опционов.
	// Если параметр не указан, будут возвращены опционы с ближайшей датой экспирации.
	ExpirationDate *date.Date `protobuf:"bytes,3,opt,name=expiration_date,json=expirationDate,proto3" json:"expiration_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OptionsChainRequest) Reset() {
	*x = OptionsChainRequest{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionsChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionsChainRequest) ProtoMessage() {}

func (x *OptionsChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionsChainRequest.ProtoReflect.Descriptor instead.
func (*OptionsChainRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{8}
}

func (x *OptionsChainRequest) GetUnderlyingSymbol() string {
	if x != nil {
		return x.UnderlyingSymbol
	}
	return ""
}

func (x *OptionsChainRequest) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *OptionsChainRequest) GetExpirationDate() *date.Date {
	if x != nil {
		return x.ExpirationDate
	}
	return nil
}

// Информация о цепочке опционов
type OptionsChainResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Символ базового актива опциона
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Информация об опционе
	Options       []*Option `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionsChainResponse) Reset() {
	*x = OptionsChainResponse{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionsChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionsChainResponse) ProtoMessage() {}

func (x *OptionsChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionsChainResponse.ProtoReflect.Descriptor instead.
func (*OptionsChainResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{9}
}

func (x *OptionsChainResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OptionsChainResponse) GetOptions() []*Option {
	if x != nil {
		return x.Options
	}
	return nil
}

// Запрос получения расписания инструмента
type ScheduleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Символ инструмента
	Symbol        string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleRequest) Reset() {
	*x = ScheduleRequest{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleRequest) ProtoMessage() {}

func (x *ScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleRequest.ProtoReflect.Descriptor instead.
func (*ScheduleRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{10}
}

func (x *ScheduleRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// Расписание инструмента
type ScheduleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Символ инструмента
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Сессии инструмента
	Sessions      []*ScheduleResponse_Sessions `protobuf:"bytes,2,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleResponse) Reset() {
	*x = ScheduleResponse{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleResponse) ProtoMessage() {}

func (x *ScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleResponse.ProtoReflect.Descriptor instead.
func (*ScheduleResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{11}
}

func (x *ScheduleResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ScheduleResponse) GetSessions() []*ScheduleResponse_Sessions {
	if x != nil {
		return x.Sessions
	}
	return nil
}

// Запрос получения времени на сервере
type ClockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClockRequest) Reset() {
	*x = ClockRequest{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClockRequest) ProtoMessage() {}

func (x *ClockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClockRequest.ProtoReflect.Descriptor instead.
func (*ClockRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{12}
}

// Время на сервере
type ClockResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Метка времени
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClockResponse) Reset() {
	*x = ClockResponse{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClockResponse) ProtoMessage() {}

func (x *ClockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClockResponse.ProtoReflect.Descriptor instead.
func (*ClockResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{13}
}

func (x *ClockResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Информация о бирже
type Exchange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Идентификатор биржи mic
	Mic string `protobuf:"bytes,1,opt,name=mic,proto3" json:"mic,omitempty"`
	// Наименование биржи
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exchange) Reset() {
	*x = Exchange{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exchange) ProtoMessage() {}

func (x *Exchange) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exchange.ProtoReflect.Descriptor instead.
func (*Exchange) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{14}
}

func (x *Exchange) GetMic() string {
	if x != nil {
		return x.Mic
	}
	return ""
}

func (x *Exchange) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Информация об инструменте
type Asset struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Символ инструмента ticker@mic
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Идентификатор инструмента
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Тикер инструмента
	Ticker string `protobuf:"bytes,3,opt,name=ticker,proto3" json:"ticker,omitempty"`
	// mic идентификатор биржи
	Mic string `protobuf:"bytes,4,opt,name=mic,proto3" json:"mic,omitempty"`
	// Isin идентификатор инструмента
	Isin string `protobuf:"bytes,5,opt,name=isin,proto3" json:"isin,omitempty"`
	// Тип инструмента
	Type string `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	// Наименование инструмента
	Name          string `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{15}
}

func (x *Asset) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Asset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Asset) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *Asset) GetMic() string {
	if x != nil {
		return x.Mic
	}
	return ""
}

func (x *Asset) GetIsin() string {
	if x != nil {
		return x.Isin
	}
	return ""
}

func (x *Asset) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Asset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Информация об опционе
type Option struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Символ инструмента
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Тип инструмента
	Type Option_Type `protobuf:"varint,2,opt,name=type,proto3,enum=grpc.tradeapi.v1.assets.Option_Type" json:"type,omitempty"`
	// Лот, количество базового актива в инструменте
	ContractSize *decimal.Decimal `protobuf:"bytes,4,opt,name=contract_size,json=contractSize,proto3" json:"contract_size,omitempty"`
	// Дата старта торговли
	TradeFirstDay *date.Date `protobuf:"bytes,5,opt,name=trade_first_day,json=tradeFirstDay,proto3" json:"trade_first_day,omitempty"`
	// Дата окончания торговли
	TradeLastDay *date.Date `protobuf:"bytes,6,opt,name=trade_last_day,json=tradeLastDay,proto3" json:"trade_last_day,omitempty"`
	// Цена исполнения опциона
	Strike *decimal.Decimal `protobuf:"bytes,7,opt,name=strike,proto3" json:"strike,omitempty"`
	// Множитель опциона
	Multiplier *decimal.Decimal `protobuf:"bytes,9,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	// Дата начала экспирации
	ExpirationFirstDay *date.Date `protobuf:"bytes,10,opt,name=expiration_first_day,json=expirationFirstDay,proto3" json:"expiration_first_day,omitempty"`
	// Дата окончания экспирации
	ExpirationLastDay *date.Date `protobuf:"bytes,11,opt,name=expiration_last_day,json=expirationLastDay,proto3" json:"expiration_last_day,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Option) Reset() {
	*x = Option{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Option) ProtoMessage() {}

func (x *Option) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Option.ProtoReflect.Descriptor instead.
func (*Option) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{16}
}

func (x *Option) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Option) GetType() Option_Type {
	if x != nil {
		return x.Type
	}
	return Option_TYPE_UNSPECIFIED
}

func (x *Option) GetContractSize() *decimal.Decimal {
	if x != nil {
		return x.ContractSize
	}
	return nil
}

func (x *Option) GetTradeFirstDay() *date.Date {
	if x != nil {
		return x.TradeFirstDay
	}
	return nil
}

func (x *Option) GetTradeLastDay() *date.Date {
	if x != nil {
		return x.TradeLastDay
	}
	return nil
}

func (x *Option) GetStrike() *decimal.Decimal {
	if x != nil {
		return x.Strike
	}
	return nil
}

func (x *Option) GetMultiplier() *decimal.Decimal {
	if x != nil {
		return x.Multiplier
	}
	return nil
}

func (x *Option) GetExpirationFirstDay() *date.Date {
	if x != nil {
		return x.ExpirationFirstDay
	}
	return nil
}

func (x *Option) GetExpirationLastDay() *date.Date {
	if x != nil {
		return x.ExpirationLastDay
	}
	return nil
}

// Доступны ли операции в Лонг
type Longable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Статус инструмента
	Value Longable_Status `protobuf:"varint,1,opt,name=value,proto3,enum=grpc.tradeapi.v1.assets.Longable_Status" json:"value,omitempty"`
	// Сколько дней действует запрет на операции в Лонг (если есть)
	HaltedDays    int32 `protobuf:"varint,2,opt,name=halted_days,json=haltedDays,proto3" json:"halted_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Longable) Reset() {
	*x = Longable{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Longable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Longable) ProtoMessage() {}

func (x *Longable) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Longable.ProtoReflect.Descriptor instead.
func (*Longable) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{17}
}

func (x *Longable) GetValue() Longable_Status {
	if x != nil {
		return x.Value
	}
	return Longable_NOT_AVAILABLE
}

func (x *Longable) GetHaltedDays() int32 {
	if x != nil {
		return x.HaltedDays
	}
	return 0
}

// Доступны ли операции в Шорт
type Shortable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Статус инструмента
	Value Shortable_Status `protobuf:"varint,1,opt,name=value,proto3,enum=grpc.tradeapi.v1.assets.Shortable_Status" json:"value,omitempty"`
	// Сколько дней действует запрет на операции в Шорт (если есть)
	HaltedDays    int32 `protobuf:"varint,2,opt,name=halted_days,json=haltedDays,proto3" json:"halted_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shortable) Reset() {
	*x = Shortable{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shortable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shortable) ProtoMessage() {}

func (x *Shortable) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shortable.ProtoReflect.Descriptor instead.
func (*Shortable) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{18}
}

func (x *Shortable) GetValue() Shortable_Status {
	if x != nil {
		return x.Value
	}
	return Shortable_NOT_AVAILABLE
}

func (x *Shortable) GetHaltedDays() int32 {
	if x != nil {
		return x.HaltedDays
	}
	return 0
}

// Сессии
type ScheduleResponse_Sessions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Тип сессии
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Интервал сессии
	Interval      *interval.Interval `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleResponse_Sessions) Reset() {
	*x = ScheduleResponse_Sessions{}
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleResponse_Sessions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleResponse_Sessions) ProtoMessage() {}

func (x *ScheduleResponse_Sessions) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleResponse_Sessions.ProtoReflect.Descriptor instead.
func (*ScheduleResponse_Sessions) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP(), []int{11, 0}
}

func (x *ScheduleResponse_Sessions) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ScheduleResponse_Sessions) GetInterval() *interval.Interval {
	if x != nil {
		return x.Interval
	}
	return nil
}

var File_grpc_tradeapi_v1_assets_assets_service_proto protoreflect.FileDescriptor

const file_grpc_tradeapi_v1_assets_assets_service_proto_rawDesc = "" +
	"\n" +
	",grpc/tradeapi/v1/assets/assets_service.proto\x12\x17grpc.tradeapi.v1.assets\x1a\x1cgoogle/api/annotations.proto\x1a\x16google/type/date.proto\x1a\x19google/type/decimal.proto\x1a\x1agoogle/type/interval.proto\x1a\x17google/type/money.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x12\n" +
	"\x10ExchangesRequest\"T\n" +
	"\x11ExchangesResponse\x12?\n" +
	"\texchanges\x18\x01 \x03(\v2!.grpc.tradeapi.v1.assets.ExchangeR\texchanges\"\x0f\n" +
	"\rAssetsRequest\"H\n" +
	"\x0eAssetsResponse\x126\n" +
	"\x06assets\x18\x01 \x03(\v2\x1e.grpc.tradeapi.v1.assets.AssetR\x06assets\"H\n" +
	"\x0fGetAssetRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\"\xe9\x02\n" +
	"\x10GetAssetResponse\x12\x14\n" +
	"\x05board\x18\x01 \x01(\tR\x05board\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x16\n" +
	"\x06ticker\x18\x03 \x01(\tR\x06ticker\x12\x10\n" +
	"\x03mic\x18\x04 \x01(\tR\x03mic\x12\x12\n" +
	"\x04isin\x18\x05 \x01(\tR\x04isin\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12\x1a\n" +
	"\bdecimals\x18\n" +
	" \x01(\x05R\bdecimals\x12\x19\n" +
	"\bmin_step\x18\v \x01(\x03R\aminStep\x12/\n" +
	"\blot_size\x18\t \x01(\v2\x14.google.type.DecimalR\alotSize\x12:\n" +
	"\x0fexpiration_date\x18\f \x01(\v2\x11.google.type.DateR\x0eexpirationDate\x12%\n" +
	"\x0equote_currency\x18\r \x01(\tR\rquoteCurrency\"N\n" +
	"\x15GetAssetParamsRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\"\xb7\x05\n" +
	"\x16GetAssetParamsResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12 \n" +
	"\ttradeable\x18\x03 \x01(\bB\x02\x18\x01R\ttradeable\x12=\n" +
	"\blongable\x18\x04 \x01(\v2!.grpc.tradeapi.v1.assets.LongableR\blongable\x12@\n" +
	"\tshortable\x18\x05 \x01(\v2\".grpc.tradeapi.v1.assets.ShortableR\tshortable\x12:\n" +
	"\x0elong_risk_rate\x18\x06 \x01(\v2\x14.google.type.DecimalR\flongRiskRate\x12?\n" +
	"\x0flong_collateral\x18\a \x01(\v2\x12.google.type.MoneyB\x02\x18\x01R\x0elongCollateral\x12<\n" +
	"\x0fshort_risk_rate\x18\b \x01(\v2\x14.google.type.DecimalR\rshortRiskRate\x12A\n" +
	"\x10short_collateral\x18\t \x01(\v2\x12.google.type.MoneyB\x02\x18\x01R\x0fshortCollateral\x12B\n" +
	"\x13long_initial_margin\x18\n" +
	" \x01(\v2\x12.google.type.MoneyR\x11longInitialMargin\x12D\n" +
	"\x14short_initial_margin\x18\v \x01(\v2\x12.google.type.MoneyR\x12shortInitialMargin\x12;\n" +
	"\vis_tradable\x18\f \x01(\v2\x1a.google.protobuf.BoolValueR\n" +
	"isTradable\"\x92\x01\n" +
	"\x13OptionsChainRequest\x12+\n" +
	"\x11underlying_symbol\x18\x01 \x01(\tR\x10underlyingSymbol\x12\x12\n" +
	"\x04root\x18\x02 \x01(\tR\x04root\x12:\n" +
	"\x0fexpiration_date\x18\x03 \x01(\v2\x11.google.type.DateR\x0eexpirationDate\"i\n" +
	"\x14OptionsChainResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x129\n" +
	"\aoptions\x18\x02 \x03(\v2\x1f.grpc.tradeapi.v1.assets.OptionR\aoptions\")\n" +
	"\x0fScheduleRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"\xcd\x01\n" +
	"\x10ScheduleResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12N\n" +
	"\bsessions\x18\x02 \x03(\v22.grpc.tradeapi.v1.assets.ScheduleResponse.SessionsR\bsessions\x1aQ\n" +
	"\bSessions\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x121\n" +
	"\binterval\x18\x02 \x01(\v2\x15.google.type.IntervalR\binterval\"\x0e\n" +
	"\fClockRequest\"I\n" +
	"\rClockResponse\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"0\n" +
	"\bExchange\x12\x10\n" +
	"\x03mic\x18\x01 \x01(\tR\x03mic\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x95\x01\n" +
	"\x05Asset\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x16\n" +
	"\x06ticker\x18\x03 \x01(\tR\x06ticker\x12\x10\n" +
	"\x03mic\x18\x04 \x01(\tR\x03mic\x12\x12\n" +
	"\x04isin\x18\x05 \x01(\tR\x04isin\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\"\xb0\x04\n" +
	"\x06Option\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x128\n" +
	"\x04type\x18\x02 \x01(\x0e2$.grpc.tradeapi.v1.assets.Option.TypeR\x04type\x129\n" +
	"\rcontract_size\x18\x04 \x01(\v2\x14.google.type.DecimalR\fcontractSize\x129\n" +
	"\x0ftrade_first_day\x18\x05 \x01(\v2\x11.google.type.DateR\rtradeFirstDay\x127\n" +
	"\x0etrade_last_day\x18\x06 \x01(\v2\x11.google.type.DateR\ftradeLastDay\x12,\n" +
	"\x06strike\x18\a \x01(\v2\x14.google.type.DecimalR\x06strike\x124\n" +
	"\n" +
	"multiplier\x18\t \x01(\v2\x14.google.type.DecimalR\n" +
	"multiplier\x12C\n" +
	"\x14expiration_first_day\x18\n" +
	" \x01(\v2\x11.google.type.DateR\x12expirationFirstDay\x12A\n" +
	"\x13expiration_last_day\x18\v \x01(\v2\x11.google.type.DateR\x11expirationLastDay\"9\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tTYPE_CALL\x10\x01\x12\f\n" +
	"\bTYPE_PUT\x10\x02\"\xb1\x01\n" +
	"\bLongable\x12>\n" +
	"\x05value\x18\x01 \x01(\x0e2(.grpc.tradeapi.v1.assets.Longable.StatusR\x05value\x12\x1f\n" +
	"\vhalted_days\x18\x02 \x01(\x05R\n" +
	"haltedDays\"D\n" +
	"\x06Status\x12\x11\n" +
	"\rNOT_AVAILABLE\x10\x00\x12\r\n" +
	"\tAVAILABLE\x10\x01\x12\x18\n" +
	"\x14ACCOUNT_NOT_APPROVED\x10\x02\"\xd4\x01\n" +
	"\tShortable\x12?\n" +
	"\x05value\x18\x01 \x01(\x0e2).grpc.tradeapi.v1.assets.Shortable.StatusR\x05value\x12\x1f\n" +
	"\vhalted_days\x18\x02 \x01(\x05R\n" +
	"haltedDays\"e\n" +
	"\x06Status\x12\x11\n" +
	"\rNOT_AVAILABLE\x10\x00\x12\r\n" +
	"\tAVAILABLE\x10\x01\x12\a\n" +
	"\x03HTB\x10\x02\x12\x18\n" +
	"\x14ACCOUNT_NOT_APPROVED\x10\x03\x12\x16\n" +
	"\x12AVAILABLE_STRATEGY\x10\x042\xf4\r\n" +
	"\rAssetsService\x12y\n" +
	"\tExchanges\x12).grpc.tradeapi.v1.assets.ExchangesRequest\x1a*.grpc.tradeapi.v1.assets.ExchangesResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/exchanges\x12m\n" +
	"\x06Assets\x12&.grpc.tradeapi.v1.assets.AssetsRequest\x1a'.grpc.tradeapi.v1.assets.AssetsResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/assets\x12\xd7\x02\n" +
	"\bGetAsset\x12(.grpc.tradeapi.v1.assets.GetAssetRequest\x1a).grpc.tradeapi.v1.assets.GetAssetResponse\"\xf5\x01\x92A\xd6\x01J\xd0\x01\n" +
	"\x03400\x12\xc8\x01\n" +
	"\xc5\x01Неверно передан символ или счет. Символ должен быть в виде ticker@mic. Где ticker - это, например, SBER. А mic, например, MISXR\x01\x01\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/assets/{symbol}\x12\xf0\x02\n" +
	"\x0eGetAssetParams\x12..grpc.tradeapi.v1.assets.GetAssetParamsRequest\x1a/.grpc.tradeapi.v1.assets.GetAssetParamsResponse\"\xfc\x01\x92A\xd6\x01J\xd0\x01\n" +
	"\x03400\x12\xc8\x01\n" +
	"\xc5\x01Неверно передан символ или счет. Символ должен быть в виде ticker@mic. Где ticker - это, например, SBER. А mic, например, MISXR\x01\x01\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/assets/{symbol}/params\x12\xe6\x02\n" +
	"\fOptionsChain\x12,.grpc.tradeapi.v1.assets.OptionsChainRequest\x1a-.grpc.tradeapi.v1.assets.OptionsChainResponse\"\xf8\x01\x92A\xc6\x01J\xc0\x01\n" +
	"\x03400\x12\xb8\x01\n" +
	"\xb5\x01Неверно передан символ. Символ должен быть в виде ticker@mic. Где ticker - это, например, SBER. А mic, например, MISXR\x01\x01\x82\xd3\xe4\x93\x02(\x12&/v1/assets/{underlying_symbol}/options\x12\xd0\x02\n" +
	"\bSchedule\x12(.grpc.tradeapi.v1.assets.ScheduleRequest\x1a).grpc.tradeapi.v1.assets.ScheduleResponse\"\xee\x01\x92A\xc6\x01J\xc0\x01\n" +
	"\x03400\x12\xb8\x01\n" +
	"\xb5\x01Неверно передан символ. Символ должен быть в виде ticker@mic. Где ticker - это, например, SBER. А mic, например, MISXR\x01\x01\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/assets/{symbol}/schedule\x12p\n" +
	"\x05Clock\x12%.grpc.tradeapi.v1.assets.ClockRequest\x1a&.grpc.tradeapi.v1.assets.ClockResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/assets/clockB\xa4\x05\x92A\xde\x04*\x01\x01Ri\n" +
	"\x03401\x12b\n" +
	"`Срок действия токена истек или токен недействителенR/\n" +
	"\x03404\x12(\n" +
	"&Инструмент не найденRy\n" +
	"\x03429\x12r\n" +
	"pСлишком много запросов. Доступный лимит - 200 запросов в минутуRZ\n" +
	"\x03500\x12S\n" +
	"QВнутренняя ошибка сервиса. Попробуйте позжеRk\n" +
	"\x03503\x12d\n" +
	"bСервис на данный момент не доступен. Попробуйте позжеRV\n" +
	"\x03504\x12O\n" +
	"MКрайний срок истек до завершения операцииR!\n" +
	"\adefault\x12\x16\x12\x14\n" +
	"\x12\x1a\x10googletypeStatusP\x01Z>github.com/FinamWeb/finam-trade-api/go/grpc/tradeapi/v1/assetsb\x06proto3"

var (
	file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescOnce sync.Once
	file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescData []byte
)

func file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescGZIP() []byte {
	file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescOnce.Do(func() {
		file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_tradeapi_v1_assets_assets_service_proto_rawDesc), len(file_grpc_tradeapi_v1_assets_assets_service_proto_rawDesc)))
	})
	return file_grpc_tradeapi_v1_assets_assets_service_proto_rawDescData
}

var file_grpc_tradeapi_v1_assets_assets_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_grpc_tradeapi_v1_assets_assets_service_proto_goTypes = []any{
	(Option_Type)(0),                  // 0: grpc.tradeapi.v1.assets.Option.Type
	(Longable_Status)(0),              // 1: grpc.tradeapi.v1.assets.Longable.Status
	(Shortable_Status)(0),             // 2: grpc.tradeapi.v1.assets.Shortable.Status
	(*ExchangesRequest)(nil),          // 3: grpc.tradeapi.v1.assets.ExchangesRequest
	(*ExchangesResponse)(nil),         // 4: grpc.tradeapi.v1.assets.ExchangesResponse
	(*AssetsRequest)(nil),             // 5: grpc.tradeapi.v1.assets.AssetsRequest
	(*AssetsResponse)(nil),            // 6: grpc.tradeapi.v1.assets.AssetsResponse
	(*GetAssetRequest)(nil),           // 7: grpc.tradeapi.v1.assets.GetAssetRequest
	(*GetAssetResponse)(nil),          // 8: grpc.tradeapi.v1.assets.GetAssetResponse
	(*GetAssetParamsRequest)(nil),     // 9: grpc.tradeapi.v1.assets.GetAssetParamsRequest
	(*GetAssetParamsResponse)(nil),    // 10: grpc.tradeapi.v1.assets.GetAssetParamsResponse
	(*OptionsChainRequest)(nil),       // 11: grpc.tradeapi.v1.assets.OptionsChainRequest
	(*OptionsChainResponse)(nil),      // 12: grpc.tradeapi.v1.assets.OptionsChainResponse
	(*ScheduleRequest)(nil),           // 13: grpc.tradeapi.v1.assets.ScheduleRequest
	(*ScheduleResponse)(nil),          // 14: grpc.tradeapi.v1.assets.ScheduleResponse
	(*ClockRequest)(nil),              // 15: grpc.tradeapi.v1.assets.ClockRequest
	(*ClockResponse)(nil),             // 16: grpc.tradeapi.v1.assets.ClockResponse
	(*Exchange)(nil),                  // 17: grpc.tradeapi.v1.assets.Exchange
	(*Asset)(nil),                     // 18: grpc.tradeapi.v1.assets.Asset
	(*Option)(nil),                    // 19: grpc.tradeapi.v1.assets.Option
	(*Longable)(nil),                  // 20: grpc.tradeapi.v1.assets.Longable
	(*Shortable)(nil),                 // 21: grpc.tradeapi.v1.assets.Shortable
	(*ScheduleResponse_Sessions)(nil), // 22: grpc.tradeapi.v1.assets.ScheduleResponse.Sessions
	(*decimal.Decimal)(nil),           // 23: google.type.Decimal
	(*date.Date)(nil),                 // 24: google.type.Date
	(*money.Money)(nil),               // 25: google.type.Money
	(*wrapperspb.BoolValue)(nil),      // 26: google.protobuf.BoolValue
	(*timestamppb.Timestamp)(nil),     // 27: google.protobuf.Timestamp
	(*interval.Interval)(nil),         // 28: google.type.Interval
}
var file_grpc_tradeapi_v1_assets_assets_service_proto_depIdxs = []int32{
	17, // 0: grpc.tradeapi.v1.assets.ExchangesResponse.exchanges:type_name -> grpc.tradeapi.v1.assets.Exchange
	18, // 1: grpc.tradeapi.v1.assets.AssetsResponse.assets:type_name -> grpc.tradeapi.v1.assets.Asset
	23, // 2: grpc.tradeapi.v1.assets.GetAssetResponse.lot_size:type_name -> google.type.Decimal
	24, // 3: grpc.tradeapi.v1.assets.GetAssetResponse.expiration_date:type_name -> google.type.Date
	20, // 4: grpc.tradeapi.v1.assets.GetAssetParamsResponse.longable:type_name -> grpc.tradeapi.v1.assets.Longable
	21, // 5: grpc.tradeapi.v1.assets.GetAssetParamsResponse.shortable:type_name -> grpc.tradeapi.v1.assets.Shortable
	23, // 6: grpc.tradeapi.v1.assets.GetAssetParamsResponse.long_risk_rate:type_name -> google.type.Decimal
	25, // 7: grpc.tradeapi.v1.assets.GetAssetParamsResponse.long_collateral:type_name -> google.type.Money
	23, // 8: grpc.tradeapi.v1.assets.GetAssetParamsResponse.short_risk_rate:type_name -> google.type.Decimal
	25, // 9: grpc.tradeapi.v1.assets.GetAssetParamsResponse.short_collateral:type_name -> google.type.Money
	25, // 10: grpc.tradeapi.v1.assets.GetAssetParamsResponse.long_initial_margin:type_name -> google.type.Money
	25, // 11: grpc.tradeapi.v1.assets.GetAssetParamsResponse.short_initial_margin:type_name -> google.type.Money
	26, // 12: grpc.tradeapi.v1.assets.GetAssetParamsResponse.is_tradable:type_name -> google.protobuf.BoolValue
	24, // 13: grpc.tradeapi.v1.assets.OptionsChainRequest.expiration_date:type_name -> google.type.Date
	19, // 14: grpc.tradeapi.v1.assets.OptionsChainResponse.options:type_name -> grpc.tradeapi.v1.assets.Option
	22, // 15: grpc.tradeapi.v1.assets.ScheduleResponse.sessions:type_name -> grpc.tradeapi.v1.assets.ScheduleResponse.Sessions
	27, // 16: grpc.tradeapi.v1.assets.ClockResponse.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 17: grpc.tradeapi.v1.assets.Option.type:type_name -> grpc.tradeapi.v1.assets.Option.Type
	23, // 18: grpc.tradeapi.v1.assets.Option.contract_size:type_name -> google.type.Decimal
	24, // 19: grpc.tradeapi.v1.assets.Option.trade_first_day:type_name -> google.type.Date
	24, // 20: grpc.tradeapi.v1.assets.Option.trade_last_day:type_name -> google.type.Date
	23, // 21: grpc.tradeapi.v1.assets.Option.strike:type_name -> google.type.Decimal
	23, // 22: grpc.tradeapi.v1.assets.Option.multiplier:type_name -> google.type.Decimal
	24, // 23: grpc.tradeapi.v1.assets.Option.expiration_first_day:type_name -> google.type.Date
	24, // 24: grpc.tradeapi.v1.assets.Option.expiration_last_day:type_name -> google.type.Date
	1,  // 25: grpc.tradeapi.v1.assets.Longable.value:type_name -> grpc.tradeapi.v1.assets.Longable.Status
	2,  // 26: grpc.tradeapi.v1.assets.Shortable.value:type_name -> grpc.tradeapi.v1.assets.Shortable.Status
	28, // 27: grpc.tradeapi.v1.assets.ScheduleResponse.Sessions.interval:type_name -> google.type.Interval
	3,  // 28: grpc.tradeapi.v1.assets.AssetsService.Exchanges:input_type -> grpc.tradeapi.v1.assets.ExchangesRequest
	5,  // 29: grpc.tradeapi.v1.assets.AssetsService.Assets:input_type -> grpc.tradeapi.v1.assets.AssetsRequest
	7,  // 30: grpc.tradeapi.v1.assets.AssetsService.GetAsset:input_type -> grpc.tradeapi.v1.assets.GetAssetRequest
	9,  // 31: grpc.tradeapi.v1.assets.AssetsService.GetAssetParams:input_type -> grpc.tradeapi.v1.assets.GetAssetParamsRequest
	11, // 32: grpc.tradeapi.v1.assets.AssetsService.OptionsChain:input_type -> grpc.tradeapi.v1.assets.OptionsChainRequest
	13, // 33: grpc.tradeapi.v1.assets.AssetsService.Schedule:input_type -> grpc.tradeapi.v1.assets.ScheduleRequest
	15, // 34: grpc.tradeapi.v1.assets.AssetsService.Clock:input_type -> grpc.tradeapi.v1.assets.ClockRequest
	4,  // 35: grpc.tradeapi.v1.assets.AssetsService.Exchanges:output_type -> grpc.tradeapi.v1.assets.ExchangesResponse
	6,  // 36: grpc.tradeapi.v1.assets.AssetsService.Assets:output_type -> grpc.tradeapi.v1.assets.AssetsResponse
	8,  // 37: grpc.tradeapi.v1.assets.AssetsService.GetAsset:output_type -> grpc.tradeapi.v1.assets.GetAssetResponse
	10, // 38: grpc.tradeapi.v1.assets.AssetsService.GetAssetParams:output_type -> grpc.tradeapi.v1.assets.GetAssetParamsResponse
	12, // 39: grpc.tradeapi.v1.assets.AssetsService.OptionsChain:output_type -> grpc.tradeapi.v1.assets.OptionsChainResponse
	14, // 40: grpc.tradeapi.v1.assets.AssetsService.Schedule:output_type -> grpc.tradeapi.v1.assets.ScheduleResponse
	16, // 41: grpc.tradeapi.v1.assets.AssetsService.Clock:output_type -> grpc.tradeapi.v1.assets.ClockResponse
	35, // [35:42] is the sub-list for method output_type
	28, // [28:35] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_grpc_tradeapi_v1_assets_assets_service_proto_init() }
func file_grpc_tradeapi_v1_assets_assets_service_proto_init() {
	if File_grpc_tradeapi_v1_assets_assets_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_tradeapi_v1_assets_assets_service_proto_rawDesc), len(file_grpc_tradeapi_v1_assets_assets_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_tradeapi_v1_assets_assets_service_proto_goTypes,
		DependencyIndexes: file_grpc_tradeapi_v1_assets_assets_service_proto_depIdxs,
		EnumInfos:         file_grpc_tradeapi_v1_assets_assets_service_proto_enumTypes,
		MessageInfos:      file_grpc_tradeapi_v1_assets_assets_service_proto_msgTypes,
	}.Build()
	File_grpc_tradeapi_v1_assets_assets_service_proto = out.File
	file_grpc_tradeapi_v1_assets_assets_service_proto_goTypes = nil
	file_grpc_tradeapi_v1_assets_assets_service_proto_depIdxs = nil
}
