// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.23.4
// source: grpc/tradeapi/v1/metrics/usage_metrics_service.proto

package usage_metrics_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UsageMetricsService_GetUsageMetrics_FullMethodName = "/grpc.tradeapi.v1.metrics.UsageMetricsService/GetUsageMetrics"
)

// UsageMetricsServiceClient is the client API for UsageMetricsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сервис для получения метрик использования TradeAPI.
// Позволяет клиентам отслеживать свою активность, включая информацию о текущих квотах и лимитах,
// чтобы избегать превышения установленных ограничений.
type UsageMetricsServiceClient interface {
	// Получение текущих метрик использования для пользователя
	// Пример HTTP запроса:
	// GET /v1/usage
	// Authorization: <token>
	GetUsageMetrics(ctx context.Context, in *GetUsageMetricsRequest, opts ...grpc.CallOption) (*GetUsageMetricsResponse, error)
}

type usageMetricsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUsageMetricsServiceClient(cc grpc.ClientConnInterface) UsageMetricsServiceClient {
	return &usageMetricsServiceClient{cc}
}

func (c *usageMetricsServiceClient) GetUsageMetrics(ctx context.Context, in *GetUsageMetricsRequest, opts ...grpc.CallOption) (*GetUsageMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUsageMetricsResponse)
	err := c.cc.Invoke(ctx, UsageMetricsService_GetUsageMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsageMetricsServiceServer is the server API for UsageMetricsService service.
// All implementations must embed UnimplementedUsageMetricsServiceServer
// for forward compatibility.
//
// Сервис для получения метрик использования TradeAPI.
// Позволяет клиентам отслеживать свою активность, включая информацию о текущих квотах и лимитах,
// чтобы избегать превышения установленных ограничений.
type UsageMetricsServiceServer interface {
	// Получение текущих метрик использования для пользователя
	// Пример HTTP запроса:
	// GET /v1/usage
	// Authorization: <token>
	GetUsageMetrics(context.Context, *GetUsageMetricsRequest) (*GetUsageMetricsResponse, error)
	mustEmbedUnimplementedUsageMetricsServiceServer()
}

// UnimplementedUsageMetricsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUsageMetricsServiceServer struct{}

func (UnimplementedUsageMetricsServiceServer) GetUsageMetrics(context.Context, *GetUsageMetricsRequest) (*GetUsageMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsageMetrics not implemented")
}
func (UnimplementedUsageMetricsServiceServer) mustEmbedUnimplementedUsageMetricsServiceServer() {}
func (UnimplementedUsageMetricsServiceServer) testEmbeddedByValue()                             {}

// UnsafeUsageMetricsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsageMetricsServiceServer will
// result in compilation errors.
type UnsafeUsageMetricsServiceServer interface {
	mustEmbedUnimplementedUsageMetricsServiceServer()
}

func RegisterUsageMetricsServiceServer(s grpc.ServiceRegistrar, srv UsageMetricsServiceServer) {
	// If the following call pancis, it indicates UnimplementedUsageMetricsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UsageMetricsService_ServiceDesc, srv)
}

func _UsageMetricsService_GetUsageMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsageMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsageMetricsServiceServer).GetUsageMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsageMetricsService_GetUsageMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsageMetricsServiceServer).GetUsageMetrics(ctx, req.(*GetUsageMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UsageMetricsService_ServiceDesc is the grpc.ServiceDesc for UsageMetricsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UsageMetricsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.tradeapi.v1.metrics.UsageMetricsService",
	HandlerType: (*UsageMetricsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsageMetrics",
			Handler:    _UsageMetricsService_GetUsageMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/tradeapi/v1/metrics/usage_metrics_service.proto",
}
