// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.23.4
// source: grpc/tradeapi/v1/metrics/usage_metrics_service.proto

package usage_metrics_service

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос получения текущих метрик использования
type GetUsageMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsageMetricsRequest) Reset() {
	*x = GetUsageMetricsRequest{}
	mi := &file_grpc_tradeapi_v1_metrics_usage_metrics_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageMetricsRequest) ProtoMessage() {}

func (x *GetUsageMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_metrics_usage_metrics_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetUsageMetricsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_metrics_usage_metrics_service_proto_rawDescGZIP(), []int{0}
}

// Информация о текущих метриках использования
type GetUsageMetricsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Список текущих квот и их использование.
	Quotas        []*GetUsageMetricsResponse_QuotaUsage `protobuf:"bytes,1,rep,name=quotas,proto3" json:"quotas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsageMetricsResponse) Reset() {
	*x = GetUsageMetricsResponse{}
	mi := &file_grpc_tradeapi_v1_metrics_usage_metrics_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageMetricsResponse) ProtoMessage() {}

func (x *GetUsageMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_metrics_usage_metrics_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetUsageMetricsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_metrics_usage_metrics_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetUsageMetricsResponse) GetQuotas() []*GetUsageMetricsResponse_QuotaUsage {
	if x != nil {
		return x.Quotas
	}
	return nil
}

// Квота
type GetUsageMetricsResponse_QuotaUsage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Название метода
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Общий лимит по данной квоте.
	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Сколько осталось доступных единиц в текущем окне.
	Remaining int64 `protobuf:"varint,3,opt,name=remaining,proto3" json:"remaining,omitempty"`
	// Время, когда счетчик квоты будет сброшен (начало нового окна).
	ResetTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=reset_time,json=resetTime,proto3" json:"reset_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsageMetricsResponse_QuotaUsage) Reset() {
	*x = GetUsageMetricsResponse_QuotaUsage{}
	mi := &file_grpc_tradeapi_v1_metrics_usage_metrics_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageMetricsResponse_QuotaUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageMetricsResponse_QuotaUsage) ProtoMessage() {}

func (x *GetUsageMetricsResponse_QuotaUsage) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_metrics_usage_metrics_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageMetricsResponse_QuotaUsage.ProtoReflect.Descriptor instead.
func (*GetUsageMetricsResponse_QuotaUsage) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_metrics_usage_metrics_service_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetUsageMetricsResponse_QuotaUsage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetUsageMetricsResponse_QuotaUsage) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUsageMetricsResponse_QuotaUsage) GetRemaining() int64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *GetUsageMetricsResponse_QuotaUsage) GetResetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ResetTime
	}
	return nil
}

var File_grpc_tradeapi_v1_metrics_usage_metrics_service_proto protoreflect.FileDescriptor

const file_grpc_tradeapi_v1_metrics_usage_metrics_service_proto_rawDesc = "" +
	"\n" +
	"4grpc/tradeapi/v1/metrics/usage_metrics_service.proto\x12\x18grpc.tradeapi.v1.metrics\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x18\n" +
	"\x16GetUsageMetricsRequest\"\x81\x02\n" +
	"\x17GetUsageMetricsResponse\x12T\n" +
	"\x06quotas\x18\x01 \x03(\v2<.grpc.tradeapi.v1.metrics.GetUsageMetricsResponse.QuotaUsageR\x06quotas\x1a\x8f\x01\n" +
	"\n" +
	"QuotaUsage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x1c\n" +
	"\tremaining\x18\x03 \x01(\x03R\tremaining\x129\n" +
	"\n" +
	"reset_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tresetTime2\xa1\x01\n" +
	"\x13UsageMetricsService\x12\x89\x01\n" +
	"\x0fGetUsageMetrics\x120.grpc.tradeapi.v1.metrics.GetUsageMetricsRequest\x1a1.grpc.tradeapi.v1.metrics.GetUsageMetricsResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/usageB.P\x01Z*trade_api/v1/metrics/usage_metrics_serviceb\x06proto3"

var (
	file_grpc_tradeapi_v1_metrics_usage_metrics_service_proto_rawDescOnce sync.Once
	file_grpc_tradeapi_v1_metrics_usage_metrics_service_proto_rawDescData []byte
)

func file_grpc_tradeapi_v1_metrics_usage_metrics_service_proto_rawDescGZIP() []byte {
	file_grpc_tradeapi_v1_metrics_usage_metrics_service_proto_rawDescOnce.Do(func() {
		file_grpc_tradeapi_v1_metrics_usage_metrics_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_tradeapi_v1_metrics_usage_metrics_service_proto_rawDesc), len(file_grpc_tradeapi_v1_metrics_usage_metrics_service_proto_rawDesc)))
	})
	return file_grpc_tradeapi_v1_metrics_usage_metrics_service_proto_rawDescData
}

var file_grpc_tradeapi_v1_metrics_usage_metrics_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_tradeapi_v1_metrics_usage_metrics_service_proto_goTypes = []any{
	(*GetUsageMetricsRequest)(nil),             // 0: grpc.tradeapi.v1.metrics.GetUsageMetricsRequest
	(*GetUsageMetricsResponse)(nil),            // 1: grpc.tradeapi.v1.metrics.GetUsageMetricsResponse
	(*GetUsageMetricsResponse_QuotaUsage)(nil), // 2: grpc.tradeapi.v1.metrics.GetUsageMetricsResponse.QuotaUsage
	(*timestamppb.Timestamp)(nil),              // 3: google.protobuf.Timestamp
}
var file_grpc_tradeapi_v1_metrics_usage_metrics_service_proto_depIdxs = []int32{
	2, // 0: grpc.tradeapi.v1.metrics.GetUsageMetricsResponse.quotas:type_name -> grpc.tradeapi.v1.metrics.GetUsageMetricsResponse.QuotaUsage
	3, // 1: grpc.tradeapi.v1.metrics.GetUsageMetricsResponse.QuotaUsage.reset_time:type_name -> google.protobuf.Timestamp
	0, // 2: grpc.tradeapi.v1.metrics.UsageMetricsService.GetUsageMetrics:input_type -> grpc.tradeapi.v1.metrics.GetUsageMetricsRequest
	1, // 3: grpc.tradeapi.v1.metrics.UsageMetricsService.GetUsageMetrics:output_type -> grpc.tradeapi.v1.metrics.GetUsageMetricsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_grpc_tradeapi_v1_metrics_usage_metrics_service_proto_init() }
func file_grpc_tradeapi_v1_metrics_usage_metrics_service_proto_init() {
	if File_grpc_tradeapi_v1_metrics_usage_metrics_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_tradeapi_v1_metrics_usage_metrics_service_proto_rawDesc), len(file_grpc_tradeapi_v1_metrics_usage_metrics_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_tradeapi_v1_metrics_usage_metrics_service_proto_goTypes,
		DependencyIndexes: file_grpc_tradeapi_v1_metrics_usage_metrics_service_proto_depIdxs,
		MessageInfos:      file_grpc_tradeapi_v1_metrics_usage_metrics_service_proto_msgTypes,
	}.Build()
	File_grpc_tradeapi_v1_metrics_usage_metrics_service_proto = out.File
	file_grpc_tradeapi_v1_metrics_usage_metrics_service_proto_goTypes = nil
	file_grpc_tradeapi_v1_metrics_usage_metrics_service_proto_depIdxs = nil
}
