// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.23.4
// source: grpc/tradeapi/v1/orders/orders_service.proto

package orders

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrdersService_PlaceOrder_FullMethodName          = "/grpc.tradeapi.v1.orders.OrdersService/PlaceOrder"
	OrdersService_CancelOrder_FullMethodName         = "/grpc.tradeapi.v1.orders.OrdersService/CancelOrder"
	OrdersService_GetOrders_FullMethodName           = "/grpc.tradeapi.v1.orders.OrdersService/GetOrders"
	OrdersService_GetOrder_FullMethodName            = "/grpc.tradeapi.v1.orders.OrdersService/GetOrder"
	OrdersService_SubscribeOrderTrade_FullMethodName = "/grpc.tradeapi.v1.orders.OrdersService/SubscribeOrderTrade"
	OrdersService_SubscribeOrders_FullMethodName     = "/grpc.tradeapi.v1.orders.OrdersService/SubscribeOrders"
	OrdersService_SubscribeTrades_FullMethodName     = "/grpc.tradeapi.v1.orders.OrdersService/SubscribeTrades"
)

// OrdersServiceClient is the client API for OrdersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сервис ордеров
type OrdersServiceClient interface {
	// Выставление биржевой заявки
	// Пример HTTP запроса:
	// POST /v1/accounts/A12345/orders
	// Content-Type: application/json
	// Authorization: <token>
	//
	//	{
	//	  "symbol": "SBER@MISX",
	//	  "quantity": {
	//				 "value": "10"
	//			 },
	//	  "side": "SIDE_BUY",
	//	  "type": "ORDER_TYPE_LIMIT",
	//	  "time_in_force": "TIME_IN_FORCE_DAY",
	//	  "limit_price": {
	//				 "value": "150.50"
	//			 }
	//	}
	//
	// Поле account_id берется из URL-пути, остальные поля передаются в теле запроса
	PlaceOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*OrderState, error)
	// Отмена биржевой заявки
	// Пример HTTP запроса:
	// DELETE /v1/accounts/A12345/orders/ORD789012
	// Authorization: <token>
	CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*OrderState, error)
	// Получение списка заявок для аккаунта
	// Пример HTTP запроса:
	// GET /v1/accounts/A12345/orders
	// Authorization: <token>
	GetOrders(ctx context.Context, in *OrdersRequest, opts ...grpc.CallOption) (*OrdersResponse, error)
	// Получение информации о конкретном ордере
	// Пример HTTP запроса:
	// GET /v1/accounts/A12345/orders/ORD789012
	// Authorization: <token>
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*OrderState, error)
	// Deprecated: Do not use.
	// Подписка на собственные заявки и сделки. Стрим метод
	SubscribeOrderTrade(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[OrderTradeRequest, OrderTradeResponse], error)
	// Подписка на собственные заявки. Стрим метод
	SubscribeOrders(ctx context.Context, in *SubscribeOrdersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeOrdersResponse], error)
	// Подписка на собственные сделки. Стрим метод
	SubscribeTrades(ctx context.Context, in *SubscribeTradesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeTradesResponse], error)
}

type ordersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrdersServiceClient(cc grpc.ClientConnInterface) OrdersServiceClient {
	return &ordersServiceClient{cc}
}

func (c *ordersServiceClient) PlaceOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*OrderState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderState)
	err := c.cc.Invoke(ctx, OrdersService_PlaceOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordersServiceClient) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*OrderState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderState)
	err := c.cc.Invoke(ctx, OrdersService_CancelOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordersServiceClient) GetOrders(ctx context.Context, in *OrdersRequest, opts ...grpc.CallOption) (*OrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrdersResponse)
	err := c.cc.Invoke(ctx, OrdersService_GetOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordersServiceClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*OrderState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderState)
	err := c.cc.Invoke(ctx, OrdersService_GetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *ordersServiceClient) SubscribeOrderTrade(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[OrderTradeRequest, OrderTradeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrdersService_ServiceDesc.Streams[0], OrdersService_SubscribeOrderTrade_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OrderTradeRequest, OrderTradeResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrdersService_SubscribeOrderTradeClient = grpc.BidiStreamingClient[OrderTradeRequest, OrderTradeResponse]

func (c *ordersServiceClient) SubscribeOrders(ctx context.Context, in *SubscribeOrdersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeOrdersResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrdersService_ServiceDesc.Streams[1], OrdersService_SubscribeOrders_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeOrdersRequest, SubscribeOrdersResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrdersService_SubscribeOrdersClient = grpc.ServerStreamingClient[SubscribeOrdersResponse]

func (c *ordersServiceClient) SubscribeTrades(ctx context.Context, in *SubscribeTradesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeTradesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrdersService_ServiceDesc.Streams[2], OrdersService_SubscribeTrades_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeTradesRequest, SubscribeTradesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrdersService_SubscribeTradesClient = grpc.ServerStreamingClient[SubscribeTradesResponse]

// OrdersServiceServer is the server API for OrdersService service.
// All implementations must embed UnimplementedOrdersServiceServer
// for forward compatibility.
//
// Сервис ордеров
type OrdersServiceServer interface {
	// Выставление биржевой заявки
	// Пример HTTP запроса:
	// POST /v1/accounts/A12345/orders
	// Content-Type: application/json
	// Authorization: <token>
	//
	//	{
	//	  "symbol": "SBER@MISX",
	//	  "quantity": {
	//				 "value": "10"
	//			 },
	//	  "side": "SIDE_BUY",
	//	  "type": "ORDER_TYPE_LIMIT",
	//	  "time_in_force": "TIME_IN_FORCE_DAY",
	//	  "limit_price": {
	//				 "value": "150.50"
	//			 }
	//	}
	//
	// Поле account_id берется из URL-пути, остальные поля передаются в теле запроса
	PlaceOrder(context.Context, *Order) (*OrderState, error)
	// Отмена биржевой заявки
	// Пример HTTP запроса:
	// DELETE /v1/accounts/A12345/orders/ORD789012
	// Authorization: <token>
	CancelOrder(context.Context, *CancelOrderRequest) (*OrderState, error)
	// Получение списка заявок для аккаунта
	// Пример HTTP запроса:
	// GET /v1/accounts/A12345/orders
	// Authorization: <token>
	GetOrders(context.Context, *OrdersRequest) (*OrdersResponse, error)
	// Получение информации о конкретном ордере
	// Пример HTTP запроса:
	// GET /v1/accounts/A12345/orders/ORD789012
	// Authorization: <token>
	GetOrder(context.Context, *GetOrderRequest) (*OrderState, error)
	// Deprecated: Do not use.
	// Подписка на собственные заявки и сделки. Стрим метод
	SubscribeOrderTrade(grpc.BidiStreamingServer[OrderTradeRequest, OrderTradeResponse]) error
	// Подписка на собственные заявки. Стрим метод
	SubscribeOrders(*SubscribeOrdersRequest, grpc.ServerStreamingServer[SubscribeOrdersResponse]) error
	// Подписка на собственные сделки. Стрим метод
	SubscribeTrades(*SubscribeTradesRequest, grpc.ServerStreamingServer[SubscribeTradesResponse]) error
	mustEmbedUnimplementedOrdersServiceServer()
}

// UnimplementedOrdersServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrdersServiceServer struct{}

func (UnimplementedOrdersServiceServer) PlaceOrder(context.Context, *Order) (*OrderState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceOrder not implemented")
}
func (UnimplementedOrdersServiceServer) CancelOrder(context.Context, *CancelOrderRequest) (*OrderState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedOrdersServiceServer) GetOrders(context.Context, *OrdersRequest) (*OrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrders not implemented")
}
func (UnimplementedOrdersServiceServer) GetOrder(context.Context, *GetOrderRequest) (*OrderState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedOrdersServiceServer) SubscribeOrderTrade(grpc.BidiStreamingServer[OrderTradeRequest, OrderTradeResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeOrderTrade not implemented")
}
func (UnimplementedOrdersServiceServer) SubscribeOrders(*SubscribeOrdersRequest, grpc.ServerStreamingServer[SubscribeOrdersResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeOrders not implemented")
}
func (UnimplementedOrdersServiceServer) SubscribeTrades(*SubscribeTradesRequest, grpc.ServerStreamingServer[SubscribeTradesResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeTrades not implemented")
}
func (UnimplementedOrdersServiceServer) mustEmbedUnimplementedOrdersServiceServer() {}
func (UnimplementedOrdersServiceServer) testEmbeddedByValue()                       {}

// UnsafeOrdersServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrdersServiceServer will
// result in compilation errors.
type UnsafeOrdersServiceServer interface {
	mustEmbedUnimplementedOrdersServiceServer()
}

func RegisterOrdersServiceServer(s grpc.ServiceRegistrar, srv OrdersServiceServer) {
	// If the following call pancis, it indicates UnimplementedOrdersServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrdersService_ServiceDesc, srv)
}

func _OrdersService_PlaceOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdersServiceServer).PlaceOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrdersService_PlaceOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdersServiceServer).PlaceOrder(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrdersService_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdersServiceServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrdersService_CancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdersServiceServer).CancelOrder(ctx, req.(*CancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrdersService_GetOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdersServiceServer).GetOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrdersService_GetOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdersServiceServer).GetOrders(ctx, req.(*OrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrdersService_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdersServiceServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrdersService_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdersServiceServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrdersService_SubscribeOrderTrade_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrdersServiceServer).SubscribeOrderTrade(&grpc.GenericServerStream[OrderTradeRequest, OrderTradeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrdersService_SubscribeOrderTradeServer = grpc.BidiStreamingServer[OrderTradeRequest, OrderTradeResponse]

func _OrdersService_SubscribeOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeOrdersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrdersServiceServer).SubscribeOrders(m, &grpc.GenericServerStream[SubscribeOrdersRequest, SubscribeOrdersResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrdersService_SubscribeOrdersServer = grpc.ServerStreamingServer[SubscribeOrdersResponse]

func _OrdersService_SubscribeTrades_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeTradesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrdersServiceServer).SubscribeTrades(m, &grpc.GenericServerStream[SubscribeTradesRequest, SubscribeTradesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrdersService_SubscribeTradesServer = grpc.ServerStreamingServer[SubscribeTradesResponse]

// OrdersService_ServiceDesc is the grpc.ServiceDesc for OrdersService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrdersService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.tradeapi.v1.orders.OrdersService",
	HandlerType: (*OrdersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlaceOrder",
			Handler:    _OrdersService_PlaceOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _OrdersService_CancelOrder_Handler,
		},
		{
			MethodName: "GetOrders",
			Handler:    _OrdersService_GetOrders_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _OrdersService_GetOrder_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeOrderTrade",
			Handler:       _OrdersService_SubscribeOrderTrade_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SubscribeOrders",
			Handler:       _OrdersService_SubscribeOrders_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeTrades",
			Handler:       _OrdersService_SubscribeTrades_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpc/tradeapi/v1/orders/orders_service.proto",
}
