// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.23.4
// source: grpc/tradeapi/v1/auth/auth_service.proto

package auth

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Уровень котировок
type MDPermission_QuoteLevel int32

const (
	// Значение не указано
	MDPermission_QUOTE_LEVEL_UNSPECIFIED MDPermission_QuoteLevel = 0
	// Последняя цена
	MDPermission_QUOTE_LEVEL_LAST_PRICE MDPermission_QuoteLevel = 1
	// Бид аск
	MDPermission_QUOTE_LEVEL_BEST_BID_OFFER MDPermission_QuoteLevel = 2
	// Агрегированный стакан
	MDPermission_QUOTE_LEVEL_DEPTH_OF_MARKET MDPermission_QuoteLevel = 3
	// Полный стакан
	MDPermission_QUOTE_LEVEL_DEPTH_OF_BOOK MDPermission_QuoteLevel = 4
	// Доступ запрещен
	MDPermission_QUOTE_LEVEL_ACCESS_FORBIDDEN MDPermission_QuoteLevel = 5
)

// Enum value maps for MDPermission_QuoteLevel.
var (
	MDPermission_QuoteLevel_name = map[int32]string{
		0: "QUOTE_LEVEL_UNSPECIFIED",
		1: "QUOTE_LEVEL_LAST_PRICE",
		2: "QUOTE_LEVEL_BEST_BID_OFFER",
		3: "QUOTE_LEVEL_DEPTH_OF_MARKET",
		4: "QUOTE_LEVEL_DEPTH_OF_BOOK",
		5: "QUOTE_LEVEL_ACCESS_FORBIDDEN",
	}
	MDPermission_QuoteLevel_value = map[string]int32{
		"QUOTE_LEVEL_UNSPECIFIED":      0,
		"QUOTE_LEVEL_LAST_PRICE":       1,
		"QUOTE_LEVEL_BEST_BID_OFFER":   2,
		"QUOTE_LEVEL_DEPTH_OF_MARKET":  3,
		"QUOTE_LEVEL_DEPTH_OF_BOOK":    4,
		"QUOTE_LEVEL_ACCESS_FORBIDDEN": 5,
	}
)

func (x MDPermission_QuoteLevel) Enum() *MDPermission_QuoteLevel {
	p := new(MDPermission_QuoteLevel)
	*p = x
	return p
}

func (x MDPermission_QuoteLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MDPermission_QuoteLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_tradeapi_v1_auth_auth_service_proto_enumTypes[0].Descriptor()
}

func (MDPermission_QuoteLevel) Type() protoreflect.EnumType {
	return &file_grpc_tradeapi_v1_auth_auth_service_proto_enumTypes[0]
}

func (x MDPermission_QuoteLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MDPermission_QuoteLevel.Descriptor instead.
func (MDPermission_QuoteLevel) EnumDescriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_auth_auth_service_proto_rawDescGZIP(), []int{4, 0}
}

// Запрос авторизации
type AuthRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// API токен (secret key)
	Secret        string `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_grpc_tradeapi_v1_auth_auth_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_auth_auth_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_auth_auth_service_proto_rawDescGZIP(), []int{0}
}

func (x *AuthRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

// Информация об авторизации
type AuthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Полученный JWT-токен
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_grpc_tradeapi_v1_auth_auth_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_auth_auth_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_auth_auth_service_proto_rawDescGZIP(), []int{1}
}

func (x *AuthResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Запрос информации о токене
type TokenDetailsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JWT-токен
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenDetailsRequest) Reset() {
	*x = TokenDetailsRequest{}
	mi := &file_grpc_tradeapi_v1_auth_auth_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenDetailsRequest) ProtoMessage() {}

func (x *TokenDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_auth_auth_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenDetailsRequest.ProtoReflect.Descriptor instead.
func (*TokenDetailsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_auth_auth_service_proto_rawDescGZIP(), []int{2}
}

func (x *TokenDetailsRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Информация о токене
type TokenDetailsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Дата и время создания
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Дата и время экспирации
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Информация о доступе к рыночным данным
	MdPermissions []*MDPermission `protobuf:"bytes,3,rep,name=md_permissions,json=mdPermissions,proto3" json:"md_permissions,omitempty"`
	// Идентификаторы аккаунтов
	AccountIds []string `protobuf:"bytes,4,rep,name=account_ids,json=accountIds,proto3" json:"account_ids,omitempty"`
	// Сессия и торговые счета в токене будут помечены readonly
	Readonly      bool `protobuf:"varint,5,opt,name=readonly,proto3" json:"readonly,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenDetailsResponse) Reset() {
	*x = TokenDetailsResponse{}
	mi := &file_grpc_tradeapi_v1_auth_auth_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenDetailsResponse) ProtoMessage() {}

func (x *TokenDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_auth_auth_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenDetailsResponse.ProtoReflect.Descriptor instead.
func (*TokenDetailsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_auth_auth_service_proto_rawDescGZIP(), []int{3}
}

func (x *TokenDetailsResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TokenDetailsResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *TokenDetailsResponse) GetMdPermissions() []*MDPermission {
	if x != nil {
		return x.MdPermissions
	}
	return nil
}

func (x *TokenDetailsResponse) GetAccountIds() []string {
	if x != nil {
		return x.AccountIds
	}
	return nil
}

func (x *TokenDetailsResponse) GetReadonly() bool {
	if x != nil {
		return x.Readonly
	}
	return false
}

// Информация о доступе к рыночным данным
type MDPermission struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Уровень котировок
	QuoteLevel MDPermission_QuoteLevel `protobuf:"varint,1,opt,name=quote_level,json=quoteLevel,proto3,enum=grpc.tradeapi.v1.auth.MDPermission_QuoteLevel" json:"quote_level,omitempty"`
	// Задержка в минутах
	DelayMinutes int32 `protobuf:"varint,2,opt,name=delay_minutes,json=delayMinutes,proto3" json:"delay_minutes,omitempty"`
	// Types that are valid to be assigned to Condition:
	//
	//	*MDPermission_Mic
	//	*MDPermission_Country
	//	*MDPermission_Continent
	//	*MDPermission_Worldwide
	Condition     isMDPermission_Condition `protobuf_oneof:"condition"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MDPermission) Reset() {
	*x = MDPermission{}
	mi := &file_grpc_tradeapi_v1_auth_auth_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MDPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MDPermission) ProtoMessage() {}

func (x *MDPermission) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_auth_auth_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MDPermission.ProtoReflect.Descriptor instead.
func (*MDPermission) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_auth_auth_service_proto_rawDescGZIP(), []int{4}
}

func (x *MDPermission) GetQuoteLevel() MDPermission_QuoteLevel {
	if x != nil {
		return x.QuoteLevel
	}
	return MDPermission_QUOTE_LEVEL_UNSPECIFIED
}

func (x *MDPermission) GetDelayMinutes() int32 {
	if x != nil {
		return x.DelayMinutes
	}
	return 0
}

func (x *MDPermission) GetCondition() isMDPermission_Condition {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *MDPermission) GetMic() string {
	if x != nil {
		if x, ok := x.Condition.(*MDPermission_Mic); ok {
			return x.Mic
		}
	}
	return ""
}

func (x *MDPermission) GetCountry() string {
	if x != nil {
		if x, ok := x.Condition.(*MDPermission_Country); ok {
			return x.Country
		}
	}
	return ""
}

func (x *MDPermission) GetContinent() string {
	if x != nil {
		if x, ok := x.Condition.(*MDPermission_Continent); ok {
			return x.Continent
		}
	}
	return ""
}

func (x *MDPermission) GetWorldwide() bool {
	if x != nil {
		if x, ok := x.Condition.(*MDPermission_Worldwide); ok {
			return x.Worldwide
		}
	}
	return false
}

type isMDPermission_Condition interface {
	isMDPermission_Condition()
}

type MDPermission_Mic struct {
	// Идентификатор биржи mic
	Mic string `protobuf:"bytes,3,opt,name=mic,proto3,oneof"`
}

type MDPermission_Country struct {
	// Страна
	Country string `protobuf:"bytes,4,opt,name=country,proto3,oneof"`
}

type MDPermission_Continent struct {
	// Континент
	Continent string `protobuf:"bytes,5,opt,name=continent,proto3,oneof"`
}

type MDPermission_Worldwide struct {
	// Весь мир
	Worldwide bool `protobuf:"varint,6,opt,name=worldwide,proto3,oneof"`
}

func (*MDPermission_Mic) isMDPermission_Condition() {}

func (*MDPermission_Country) isMDPermission_Condition() {}

func (*MDPermission_Continent) isMDPermission_Condition() {}

func (*MDPermission_Worldwide) isMDPermission_Condition() {}

// Запрос подписки на обновление JWT токена
type SubscribeJwtRenewalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// API токен (secret key)
	Secret        string `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeJwtRenewalRequest) Reset() {
	*x = SubscribeJwtRenewalRequest{}
	mi := &file_grpc_tradeapi_v1_auth_auth_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeJwtRenewalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeJwtRenewalRequest) ProtoMessage() {}

func (x *SubscribeJwtRenewalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_auth_auth_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeJwtRenewalRequest.ProtoReflect.Descriptor instead.
func (*SubscribeJwtRenewalRequest) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_auth_auth_service_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeJwtRenewalRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

// Обновленный токен. Стрим
type SubscribeJwtRenewalResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Полученный JWT-токен
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeJwtRenewalResponse) Reset() {
	*x = SubscribeJwtRenewalResponse{}
	mi := &file_grpc_tradeapi_v1_auth_auth_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeJwtRenewalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeJwtRenewalResponse) ProtoMessage() {}

func (x *SubscribeJwtRenewalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_tradeapi_v1_auth_auth_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeJwtRenewalResponse.ProtoReflect.Descriptor instead.
func (*SubscribeJwtRenewalResponse) Descriptor() ([]byte, []int) {
	return file_grpc_tradeapi_v1_auth_auth_service_proto_rawDescGZIP(), []int{6}
}

func (x *SubscribeJwtRenewalResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_grpc_tradeapi_v1_auth_auth_service_proto protoreflect.FileDescriptor

const file_grpc_tradeapi_v1_auth_auth_service_proto_rawDesc = "" +
	"\n" +
	"(grpc/tradeapi/v1/auth/auth_service.proto\x12\x15grpc.tradeapi.v1.auth\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"%\n" +
	"\vAuthRequest\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\"$\n" +
	"\fAuthResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"+\n" +
	"\x13TokenDetailsRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x95\x02\n" +
	"\x14TokenDetailsResponse\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12J\n" +
	"\x0emd_permissions\x18\x03 \x03(\v2#.grpc.tradeapi.v1.auth.MDPermissionR\rmdPermissions\x12\x1f\n" +
	"\vaccount_ids\x18\x04 \x03(\tR\n" +
	"accountIds\x12\x1a\n" +
	"\breadonly\x18\x05 \x01(\bR\breadonly\"\xcb\x03\n" +
	"\fMDPermission\x12O\n" +
	"\vquote_level\x18\x01 \x01(\x0e2..grpc.tradeapi.v1.auth.MDPermission.QuoteLevelR\n" +
	"quoteLevel\x12#\n" +
	"\rdelay_minutes\x18\x02 \x01(\x05R\fdelayMinutes\x12\x12\n" +
	"\x03mic\x18\x03 \x01(\tH\x00R\x03mic\x12\x1a\n" +
	"\acountry\x18\x04 \x01(\tH\x00R\acountry\x12\x1e\n" +
	"\tcontinent\x18\x05 \x01(\tH\x00R\tcontinent\x12\x1e\n" +
	"\tworldwide\x18\x06 \x01(\bH\x00R\tworldwide\"\xc7\x01\n" +
	"\n" +
	"QuoteLevel\x12\x1b\n" +
	"\x17QUOTE_LEVEL_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16QUOTE_LEVEL_LAST_PRICE\x10\x01\x12\x1e\n" +
	"\x1aQUOTE_LEVEL_BEST_BID_OFFER\x10\x02\x12\x1f\n" +
	"\x1bQUOTE_LEVEL_DEPTH_OF_MARKET\x10\x03\x12\x1d\n" +
	"\x19QUOTE_LEVEL_DEPTH_OF_BOOK\x10\x04\x12 \n" +
	"\x1cQUOTE_LEVEL_ACCESS_FORBIDDEN\x10\x05B\v\n" +
	"\tcondition\"4\n" +
	"\x1aSubscribeJwtRenewalRequest\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\"3\n" +
	"\x1bSubscribeJwtRenewalResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2\x82\x03\n" +
	"\vAuthService\x12h\n" +
	"\x04Auth\x12\".grpc.tradeapi.v1.auth.AuthRequest\x1a#.grpc.tradeapi.v1.auth.AuthResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/sessions\x12\x88\x01\n" +
	"\fTokenDetails\x12*.grpc.tradeapi.v1.auth.TokenDetailsRequest\x1a+.grpc.tradeapi.v1.auth.TokenDetailsResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/sessions/details\x12~\n" +
	"\x13SubscribeJwtRenewal\x121.grpc.tradeapi.v1.auth.SubscribeJwtRenewalRequest\x1a2.grpc.tradeapi.v1.auth.SubscribeJwtRenewalResponse0\x01B\xdc\x05\x92A\x98\x05*\x01\x01Ri\n" +
	"\x03400\x12b\n" +
	"`Срок действия токена истек или токен недействителенRi\n" +
	"\x03401\x12b\n" +
	"`Срок действия токена истек или токен недействителенRy\n" +
	"\x03429\x12r\n" +
	"pСлишком много запросов. Доступный лимит - 200 запросов в минутуRZ\n" +
	"\x03500\x12S\n" +
	"QВнутренняя ошибка сервиса. Попробуйте позжеRk\n" +
	"\x03503\x12d\n" +
	"bСервис на данный момент не доступен. Попробуйте позжеRV\n" +
	"\x03504\x12O\n" +
	"MКрайний срок истек до завершения операцииR!\n" +
	"\adefault\x12\x16\x12\x14\n" +
	"\x12\x1a\x10googletypeStatusP\x01Z<github.com/FinamWeb/finam-trade-api/go/grpc/tradeapi/v1/authb\x06proto3"

var (
	file_grpc_tradeapi_v1_auth_auth_service_proto_rawDescOnce sync.Once
	file_grpc_tradeapi_v1_auth_auth_service_proto_rawDescData []byte
)

func file_grpc_tradeapi_v1_auth_auth_service_proto_rawDescGZIP() []byte {
	file_grpc_tradeapi_v1_auth_auth_service_proto_rawDescOnce.Do(func() {
		file_grpc_tradeapi_v1_auth_auth_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_tradeapi_v1_auth_auth_service_proto_rawDesc), len(file_grpc_tradeapi_v1_auth_auth_service_proto_rawDesc)))
	})
	return file_grpc_tradeapi_v1_auth_auth_service_proto_rawDescData
}

var file_grpc_tradeapi_v1_auth_auth_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_tradeapi_v1_auth_auth_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_grpc_tradeapi_v1_auth_auth_service_proto_goTypes = []any{
	(MDPermission_QuoteLevel)(0),        // 0: grpc.tradeapi.v1.auth.MDPermission.QuoteLevel
	(*AuthRequest)(nil),                 // 1: grpc.tradeapi.v1.auth.AuthRequest
	(*AuthResponse)(nil),                // 2: grpc.tradeapi.v1.auth.AuthResponse
	(*TokenDetailsRequest)(nil),         // 3: grpc.tradeapi.v1.auth.TokenDetailsRequest
	(*TokenDetailsResponse)(nil),        // 4: grpc.tradeapi.v1.auth.TokenDetailsResponse
	(*MDPermission)(nil),                // 5: grpc.tradeapi.v1.auth.MDPermission
	(*SubscribeJwtRenewalRequest)(nil),  // 6: grpc.tradeapi.v1.auth.SubscribeJwtRenewalRequest
	(*SubscribeJwtRenewalResponse)(nil), // 7: grpc.tradeapi.v1.auth.SubscribeJwtRenewalResponse
	(*timestamppb.Timestamp)(nil),       // 8: google.protobuf.Timestamp
}
var file_grpc_tradeapi_v1_auth_auth_service_proto_depIdxs = []int32{
	8, // 0: grpc.tradeapi.v1.auth.TokenDetailsResponse.created_at:type_name -> google.protobuf.Timestamp
	8, // 1: grpc.tradeapi.v1.auth.TokenDetailsResponse.expires_at:type_name -> google.protobuf.Timestamp
	5, // 2: grpc.tradeapi.v1.auth.TokenDetailsResponse.md_permissions:type_name -> grpc.tradeapi.v1.auth.MDPermission
	0, // 3: grpc.tradeapi.v1.auth.MDPermission.quote_level:type_name -> grpc.tradeapi.v1.auth.MDPermission.QuoteLevel
	1, // 4: grpc.tradeapi.v1.auth.AuthService.Auth:input_type -> grpc.tradeapi.v1.auth.AuthRequest
	3, // 5: grpc.tradeapi.v1.auth.AuthService.TokenDetails:input_type -> grpc.tradeapi.v1.auth.TokenDetailsRequest
	6, // 6: grpc.tradeapi.v1.auth.AuthService.SubscribeJwtRenewal:input_type -> grpc.tradeapi.v1.auth.SubscribeJwtRenewalRequest
	2, // 7: grpc.tradeapi.v1.auth.AuthService.Auth:output_type -> grpc.tradeapi.v1.auth.AuthResponse
	4, // 8: grpc.tradeapi.v1.auth.AuthService.TokenDetails:output_type -> grpc.tradeapi.v1.auth.TokenDetailsResponse
	7, // 9: grpc.tradeapi.v1.auth.AuthService.SubscribeJwtRenewal:output_type -> grpc.tradeapi.v1.auth.SubscribeJwtRenewalResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_grpc_tradeapi_v1_auth_auth_service_proto_init() }
func file_grpc_tradeapi_v1_auth_auth_service_proto_init() {
	if File_grpc_tradeapi_v1_auth_auth_service_proto != nil {
		return
	}
	file_grpc_tradeapi_v1_auth_auth_service_proto_msgTypes[4].OneofWrappers = []any{
		(*MDPermission_Mic)(nil),
		(*MDPermission_Country)(nil),
		(*MDPermission_Continent)(nil),
		(*MDPermission_Worldwide)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_tradeapi_v1_auth_auth_service_proto_rawDesc), len(file_grpc_tradeapi_v1_auth_auth_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_tradeapi_v1_auth_auth_service_proto_goTypes,
		DependencyIndexes: file_grpc_tradeapi_v1_auth_auth_service_proto_depIdxs,
		EnumInfos:         file_grpc_tradeapi_v1_auth_auth_service_proto_enumTypes,
		MessageInfos:      file_grpc_tradeapi_v1_auth_auth_service_proto_msgTypes,
	}.Build()
	File_grpc_tradeapi_v1_auth_auth_service_proto = out.File
	file_grpc_tradeapi_v1_auth_auth_service_proto_goTypes = nil
	file_grpc_tradeapi_v1_auth_auth_service_proto_depIdxs = nil
}
