// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.23.4
// source: grpc/tradeapi/v1/auth/auth_service.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_Auth_FullMethodName                = "/grpc.tradeapi.v1.auth.AuthService/Auth"
	AuthService_TokenDetails_FullMethodName        = "/grpc.tradeapi.v1.auth.AuthService/TokenDetails"
	AuthService_SubscribeJwtRenewal_FullMethodName = "/grpc.tradeapi.v1.auth.AuthService/SubscribeJwtRenewal"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сервис аутентификации
type AuthServiceClient interface {
	// Получение JWT токена из API токена
	// Пример HTTP запроса:
	// POST /v1/sessions
	// Content-Type: application/json
	//
	//	{
	//	  "secret": "your-api-secret-key"
	//	}
	//
	// Все поля передаются в теле запроса
	Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// Получение информации о токене сессии
	// Пример HTTP запроса:
	// POST /v1/sessions/details
	// Content-Type: application/json
	//
	//	{
	//	  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
	//	}
	//
	// Токен передается в теле запроса для безопасности
	// Получение информации о токене. Также включает список доступных счетов.
	TokenDetails(ctx context.Context, in *TokenDetailsRequest, opts ...grpc.CallOption) (*TokenDetailsResponse, error)
	// Подписка на обновление JWT токена. Стрим метод
	SubscribeJwtRenewal(ctx context.Context, in *SubscribeJwtRenewalRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeJwtRenewalResponse], error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, AuthService_Auth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) TokenDetails(ctx context.Context, in *TokenDetailsRequest, opts ...grpc.CallOption) (*TokenDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenDetailsResponse)
	err := c.cc.Invoke(ctx, AuthService_TokenDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) SubscribeJwtRenewal(ctx context.Context, in *SubscribeJwtRenewalRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeJwtRenewalResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AuthService_ServiceDesc.Streams[0], AuthService_SubscribeJwtRenewal_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeJwtRenewalRequest, SubscribeJwtRenewalResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AuthService_SubscribeJwtRenewalClient = grpc.ServerStreamingClient[SubscribeJwtRenewalResponse]

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
//
// Сервис аутентификации
type AuthServiceServer interface {
	// Получение JWT токена из API токена
	// Пример HTTP запроса:
	// POST /v1/sessions
	// Content-Type: application/json
	//
	//	{
	//	  "secret": "your-api-secret-key"
	//	}
	//
	// Все поля передаются в теле запроса
	Auth(context.Context, *AuthRequest) (*AuthResponse, error)
	// Получение информации о токене сессии
	// Пример HTTP запроса:
	// POST /v1/sessions/details
	// Content-Type: application/json
	//
	//	{
	//	  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
	//	}
	//
	// Токен передается в теле запроса для безопасности
	// Получение информации о токене. Также включает список доступных счетов.
	TokenDetails(context.Context, *TokenDetailsRequest) (*TokenDetailsResponse, error)
	// Подписка на обновление JWT токена. Стрим метод
	SubscribeJwtRenewal(*SubscribeJwtRenewalRequest, grpc.ServerStreamingServer[SubscribeJwtRenewalResponse]) error
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) Auth(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
}
func (UnimplementedAuthServiceServer) TokenDetails(context.Context, *TokenDetailsRequest) (*TokenDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TokenDetails not implemented")
}
func (UnimplementedAuthServiceServer) SubscribeJwtRenewal(*SubscribeJwtRenewalRequest, grpc.ServerStreamingServer[SubscribeJwtRenewalResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeJwtRenewal not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Auth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Auth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_TokenDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).TokenDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_TokenDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).TokenDetails(ctx, req.(*TokenDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_SubscribeJwtRenewal_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeJwtRenewalRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AuthServiceServer).SubscribeJwtRenewal(m, &grpc.GenericServerStream[SubscribeJwtRenewalRequest, SubscribeJwtRenewalResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AuthService_SubscribeJwtRenewalServer = grpc.ServerStreamingServer[SubscribeJwtRenewalResponse]

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.tradeapi.v1.auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _AuthService_Auth_Handler,
		},
		{
			MethodName: "TokenDetails",
			Handler:    _AuthService_TokenDetails_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeJwtRenewal",
			Handler:       _AuthService_SubscribeJwtRenewal_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpc/tradeapi/v1/auth/auth_service.proto",
}
